version: '3.4'

services:
  bloo:
    container_name: bloo
    build:
      context: .
      dockerfile: Dockerfile.production
      network: host
    restart: always
    volumes:
        - ./bloo_ai.txt:/usr/src/app/bloo_ai.txt 
    network_mode: host # comment this out if you want to use dockerized mongo
    # also, if you want to use dockerized Mongo you need to change DB_HOST to "mongo" in .env

#####
# uncomment the following to use dockerized mongo
    # depends_on:
    #   - mongo
  # mongo:
  #   image: mongo
  #   restart: unless-stopped
  #   # environment:
  #     # MONGO_INITDB_ROOT_USERNAME: root
  #     # MONGO_INITDB_ROOT_PASSWORD: example
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./mongo_data:/data/db

  # mongo-express:
  #   image: mongo-express
  #   restart: unless-stopped
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     # ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     # ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/